# constants.py

TEMPLATE_1_SETUP_CONFIG = 1
TEMPLATE_2_SETUP_LOCATION = 2

TEMPLATE_1_SETUP_CONFIG_FILE_PREFIX = "Envizi_SetupConfig_"
TEMPLATE_2_SETUP_LOCATION_FILE_PREFIX = "Envizi_SetupLocation_"

TEMPLATE_1_SETUP_CONFIG_SHEET_NAME = "Setup"
TEMPLATE_2_SETUP_LOCATION_SHEET_NAME = "Setup"

